---
# global vars
#kafka_version: 3.8.0
kafka_install_directory: /etc/kafka
kafka_config_directory: '{{ kafka_install_directory }}/config'
kafka_bin_directory: '{{ kafka_install_directory }}/bin'
kafka_data_directory: /var/lib/kafka
kafka_log_directory: /var/log/kafka

# ssl
kafka_ssl_directory: '{{ kafka_install_directory }}/ssl'
kafka_ssl_ca_directory: '{{ kafka_ssl_directory }}/ca'
kafka_ssl_req_directory: '{{ kafka_ssl_directory }}/req'
kafka_ssl_key_directory: '{{ kafka_ssl_directory }}/key'
kafka_ssl_cert_directory: '{{ kafka_ssl_directory }}/cert'
kafka_ssl_keystore_directory: '{{ kafka_ssl_directory }}/keystore'
kafka_ssl_truststore_directory: '{{ kafka_ssl_directory }}/truststore'
