---
# roles/common/tasks

# common tasks for all instances
- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: full

- name: install basic packages
  apt:
    pkg:
    - ntp
    - wget 
    - curl
    - htop
    - rsync
    - python3
    - python3-passlib
    - fail2ban
    - default-jdk
    - acl
    state: latest
  register: package_updates

- name: fail2ban jail.local
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: yes
  notify: start fail2ban

- name: secure ssh configs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^\#?PermitRootLogin (yes|no)', line: 'PermitRootLogin without-password' }
    - { regexp: '^\#?PasswordAuthentication (yes|no)', line: 'PasswordAuthentication no' }
    - { regexp: '^\#?PubkeyAuthentication (yes|no)', line: 'PubkeyAuthentication yes' }
  notify: restart ssh

- name: set hard nofile limit
  community.general.pam_limits:
    domain: '{{ item.domain }}'
    limit_type: '-'
    limit_item: nofile
    value: '{{ item.value }}'
  loop:
    - domain: '*'
      value: 1048576
    - domain: 'root'
      value: 16777216

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: reboot linode
  reboot:
  when:
    - reboot_required_file.stat.exists == true
