---
# configure kafka 

- name: create kafka data and log directory
  file:
    path: "{{ kafka_log_directory }}"
    state: directory
    mode: 0755
    owner: kafka
    group: kafka
  when:
    - hostvars[inventory_hostname].region == region_name

- name: backup server and broker properties
  copy:
    src: "{{ kafka_config_directory }}/{{ item.config }}"
    dest: "{{ kafka_config_directory }}/{{ item.config }}.bak"
    owner: kafka
    group: kafka
    mode: 0644
    remote_src: true
  loop:
    - { config: 'kraft/server.properties' }
    - { config: 'kraft/broker.properties' }

- name: 'subset of {{ region_name }} servers'
  set_fact:
    cluster_servers: '{{ (kafka_data.server | selectattr("instance.region", "eq", region_name))[0:3]
                         | map(attribute="instance.hostname") }}'
  run_once: true
  delegate_to: localhost

- name: '{{ region_name }} bootstrap servers'
  set_fact:
    region_bootstrap_servers: '{{ cluster_servers
                                   | zip_longest([], fillvalue=":9092")
                                   | map("join") }}'
  run_once: true
  delegate_to: localhost

- name: '{{ region_name }} servers and voters'
  set_fact:
    region_bootstrap_servers: '{{ region_bootstrap_servers | join(", ") }}'
    quorum_voters: '{{ query("sequence", "", start=1, count=3, format="%d@")
                       | zip(region_bootstrap_servers)
                       | map("join")
                       | join(", ") }}'
  run_once: true
  delegate_to: localhost

- name: updating kafka config for controllers and brokers
  template:
    src: templates/{{ server_properties | basename }}.j2
    dest: "{{ server_properties }}"
    owner: kafka
    group: kafka
    mode: 0644
    backup: true
    force: true
  vars:
    node_id: '{{ (groups[region_name] | index_of("eq", inventory_hostname)) + 1 }}'
    listener: '{{ hostname_map[inventory_hostname].instance.hostname }}'
    server_properties: "{{ role_properties[hostvars[inventory_hostname].role] }}"

- name: check existing kafka cluster uuid
  shell:
    cmd: grep -s cluster.id {{ kafka_data_directory }}/data/kraft-combined-logs/meta.properties | cut -f 2 -d = || /bin/true
    removes: "{{ kafka_data_directory}}/data/kraft-combined-logs/meta.properties"
  register: old_cluster_uuid
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: create kafka cluster uuid
  command:
    cmd:  "{{ kafka_bin_directory }}/kafka-storage.sh random-uuid"
    creates: "{{ kafka_data_directory}}/data/kraft-combined-logs/meta.properties"
  register: new_cluster_uuid
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: determine kafka cluster uuid
  set_fact:
    cluster_uuid: "{{ (old_cluster_uuid.changed) | ternary(old_cluster_uuid.stdout, new_cluster_uuid.stdout) }}"
  run_once: true
  delegate_to: localhost

- name: format data directory for controllers and brokers
  command:
    cmd: "{{ kafka_bin_directory }}/kafka-storage.sh format -t {{ cluster_uuid}} -c {{ server_properties }} --ignore-formatted"
  become: true
  become_user: kafka
  vars:
    server_properties: "{{ role_properties[hostvars[inventory_hostname].role] }}"
  when:
    - hostvars[inventory_hostname].region == region_name
