---
# configure kafka

- name: remote region is the first region that is not the current region
  set_fact:
    remote_region: '{{ ([region] | flatten | select("!=", region_name))[0] }}'
  run_once: true
  delegate_to: localhost

- name: 'remote region ({{ remote_region }}) bootstrap servers'
  set_fact:
    remote_bootstrap_servers: '{{ (kafka_data.server
                                     | selectattr("instance.region", "eq", remote_region))[0:controller_count]
                                   | map(attribute="instance.hostname")
                                   | product([":9092"])
                                   | map("join")
                                   | join(", ") }}'
  run_once: true
  delegate_to: localhost

- name: 'subset of {{ region_name }} servers'
  set_fact:
    cluster_servers: '{{ (kafka_data.server | selectattr("instance.region", "eq", region_name))[0:controller_count]
                         | map(attribute="instance.hostname") }}'
  run_once: true
  delegate_to: localhost

- name: '{{ region_name }} servers and voters'
  set_fact:
    region_bootstrap_servers: '{{ cluster_servers | product([":9092"]) | map("join") | join(", ") }}'
    quorum_voters: '{{ query("sequence", "", start=1, count=controller_count, format="%d@")
                       | zip_longest(cluster_servers, [], fillvalue=":9093")
                       | map("join")
                       | join(", ") }}'
  run_once: true
  delegate_to: localhost

- name: updating kafka config for controllers and brokers
  template:
    src: templates/server.properties.j2
    dest: "{{ kafka_config_directory }}/kraft/server.properties"
    owner: kafka
    group: kafka
    mode: 0644
    backup: true
    force: true
  vars:
    node_id: '{{ (groups[region_name] | ansible.utils.index_of("eq", inventory_hostname)) + 1 }}'
    listener: '{{ hostname_map[inventory_hostname].instance.hostname }}'
    server_roles: '{{ hostvars[inventory_hostname].role | regex_replace(" only", "") | split(" and ") }}'
  when:
    - hostvars[inventory_hostname].region == region_name

# mirror-maker for servers that are controllers
- name: updating kafka mirror maker config for controllers
  template:
    src: templates/connect-mirror-maker.properties.j2
    dest: "{{ kafka_config_directory }}/connect-mirror-maker.properties"
    owner: kafka
    group: kafka
    mode: 0644
    backup: true
    force: true
  vars:
    listener: '{{ hostname_map[inventory_hostname].instance.hostname }}'
  when:
    - hostvars[inventory_hostname].region == region_name
    - '"controller" in hostvars[inventory_hostname].role'

- name: check existing kafka cluster uuid
  shell:
    cmd: grep -s cluster.id {{ kafka_data_directory }}/data/kraft-metadata-logs/meta.properties | cut -f 2 -d = || /bin/true
    removes: "{{ kafka_data_directory}}/data/kraft-metadata-logs/meta.properties"
  register: old_cluster_uuid
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: create kafka cluster uuid
  command:
    cmd:  "{{ kafka_bin_directory }}/kafka-storage.sh random-uuid"
    creates: "{{ kafka_data_directory}}/data/kraft-metadata-logs/meta.properties"
  register: new_cluster_uuid
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: determine kafka cluster uuid
  set_fact:
    cluster_uuid: "{{ (old_cluster_uuid.changed) | ternary(old_cluster_uuid.stdout, new_cluster_uuid.stdout) }}"
  run_once: true
  delegate_to: localhost

- name: format data directory for controllers and brokers
  command:
    cmd: "{{ kafka_bin_directory }}/kafka-storage.sh format -t {{ cluster_uuid}} -c {{ kafka_config_directory }}/kraft/server.properties --ignore-formatted"
  become: true
  become_user: kafka
  when:
    - hostvars[inventory_hostname].region == region_name
