---
# configure kafka 

- name: create kafka data and log directory
  file:
    path: "{{ kafka_log_directory }}"
    state: directory
    mode: 0755
    owner: kafka
    group: kafka
  when:
    - hostvars[inventory_hostname].region == region_name

- name: backup server and broker properties
  copy:
    src: "{{ kafka_config_directory }}/{{ item.config }}"
    dest: "{{ kafka_config_directory }}/{{ item.config }}.bak"
    owner: kafka
    group: kafka
    mode: 0644
    remote_src: true
  loop:
    - { config: 'kraft/server.properties' }
    - { config: 'kraft/broker.properties' }

- name: 'subset of {{ region_name }} servers'
  set_fact:
    cluster_servers: '{{ (kafka_data.server | selectattr("instance.region", "eq", region_name))[0:3]
                         | map(attribute="instance.hostname") }}'
  run_once: true
  delegate_to: localhost

- name: '{{ region_name }} bootstrap servers'
  set_fact:
    region_bootstrap_servers: '{{ cluster_servers
                                   | zip_longest([], fillvalue=":9092")
                                   | map("join") }}'

- name: '{{ region_name }} servers and voters'
  set_fact:
    region_bootstrap_servers: '{{ region_bootstrap_servers | join(", ") }}'
    quorum_voters: '{{ query("sequence", "", start=1, count=3, format="%d@")
                       | zip(region_bootstrap_servers)
                       | map("join")
                       | join(", ") }}'
  run_once: true
  delegate_to: localhost

# for servers that are controller and broker roles
- name: updating kafka config for controller and broker
  template:
    src: templates/server.properties.j2
    dest: "{{ kafka_config_directory }}/kraft/server.properties"
    owner: kafka
    group: kafka
    mode: 0644
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups[region_name] }}"
  loop_control:
    index_var: count
  when: hostvars[groups[region_name][count]].role == 'controller and broker'

# for servers who are brokers only
- name: updating kafka config for broker only
  template:
    src: templates/broker.properties.j2
    dest: "{{ kafka_config_directory }}/kraft/broker.properties"
    owner: kafka
    group: kafka
    mode: 0644
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups[region_name] }}"
  loop_control:
    index_var: count
  when: hostvars[groups[region_name][count]].role == 'broker only'

- name: check existing kafka cluster uuid
  shell:
    cmd: grep -s cluster.id {{ kafka_data_directory }}/data/kraft-combined-logs/meta.properties | cut -f 2 -d = || /bin/true
    removes: "{{ kafka_data_directory}}/data/kraft-combined-logs/meta.properties"
  register: old_cluster_uuid
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: create kafka cluster uuid
  command:
    cmd:  "{{ kafka_bin_directory }}/kafka-storage.sh random-uuid"
    creates: "{{ kafka_data_directory}}/data/kraft-combined-logs/meta.properties"
  register: new_cluster_uuid
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: determine kafka cluster uuid
  set_fact:
    cluster_uuid: "{{ (old_cluster_uuid.changed) | ternary(old_cluster_uuid.stdout, new_cluster_uuid.stdout) }}"
  run_once: true
  delegate_to: "{{ groups[region_name][0] }}"

- name: format data directory for controller and broker nodes
  command:
    cmd: "{{ kafka_bin_directory }}/kafka-storage.sh format -t {{ cluster_uuid}} -c {{ kafka_config_directory }}/kraft/server.properties --ignore-formatted"
  become: true
  become_user: kafka
  when:
    - hostvars[inventory_hostname].region == region_name
    - hostvars[inventory_hostname].role == 'controller and broker'

- name: format data directory broker nodes
  command:
    cmd: "{{ kafka_bin_directory }}/kafka-storage.sh format -t {{ cluster_uuid}} -c {{ kafka_config_directory }}/kraft/broker.properties --ignore-formatted"
  become: true
  become_user: kafka
  when:
    - hostvars[inventory_hostname].region == region_name
    - hostvars[inventory_hostname].role == 'broker only'
