---
# configure hostname and hosts file

- name: update /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} KAFKA HOSTS"
    block: |
      #jinja2: trim_blocks:False
      {%- for server in kafka_data.server %}
      {%- if server.instance.region == hostvars[inventory_hostname].region %}
      {{ server.instance.ip_priv1 }} {{ server.instance.hostname }} {{ server.name }}
      {%- else %}
      {{ server.instance.ip_pub1 }} {{ server.instance.hostname }} {{ server.name }}
      {%- endif %}
      {%- endfor %}

- name: configure hostnames
  hostname:
    use: systemd
    name: "{{ kafka_data.server[count].instance.hostname }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['kafka'] }}"
  loop_control:
    index_var: count
