---
# main

- name: map inventory hosts to group vars
  set_fact:
    hostname_map: '{{ dict(groups["kafka"] | zip(kafka_data.server) ) }}'
  run_once: true
  delegate_to: localhost

- name: configure hostname
  import_tasks: hostname.yml

- name: create kafka user
  import_tasks: user.yml

- name: installing kafka
  import_tasks: install.yml

- name: configure cluster certs
  import_tasks: ssl.yml

- name: configure kafka
  include_tasks: configure.yml
  loop: '{{ [region] | flatten }}'
  loop_control:
    loop_var: region_name
  when: hostvars[inventory_hostname].region == region_name

- name: setup application log cleanup
  include_tasks: logrotate.yml

- name: starting kafka
  systemd:
    name: kafka
    state: started
    enabled: true
    daemon_reload: true

- name: starting mirror-maker
  systemd:
    name: mirror-maker
    state: restarted
    enabled: true
    daemon_reload: true
  when:
    - '"controller" in hostvars[inventory_hostname].role'
