---
# create cluster ssl certificates

- set_fact:
    cert_validity: +90d
  name: set cert validity
  when: not cert_validity|d(False)
  run_once: true
  delegate_to: localhost

- set_fact:
    client_list: "{{ query('sequence', '', count=client_count, format='client%d') }}"
  name: generate list of client certs
  run_once: true
  delegate_to: localhost

- name: create kafka ssl directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: kafka
    group: kafka
  loop:
    - '{{ kafka_ssl_directory }}'
    - '{{ kafka_ssl_ca_directory }}'
    - '{{ kafka_ssl_req_directory }}'
    - '{{ kafka_ssl_key_directory }}'
    - '{{ kafka_ssl_cert_directory }}'
    - '{{ kafka_ssl_keystore_directory }}'
    - '{{ kafka_ssl_truststore_directory }}'

# create root ca for signing
- name: generate ca key
  community.crypto.openssl_privatekey:
    path: '{{ kafka_ssl_ca_directory }}/ca-key'
    passphrase: '{{ ca_password }}'
    cipher: auto
    return_content: true
    owner: kafka
    group: kafka
  no_log: true
  register: ca_key
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - ca_cert

- name: generate ca csr
  community.crypto.openssl_csr:
    path: '{{ kafka_ssl_ca_directory }}/ca-csr'
    privatekey_path: '{{ kafka_ssl_ca_directory }}/ca-key'
    privatekey_passphrase: '{{ ca_password }}'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ ca_common_name }}'
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
    owner: kafka
    group: kafka
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - ca_cert

- name: generate ca crt
  community.crypto.x509_certificate:
    path: '{{ kafka_ssl_ca_directory }}/ca-crt'
    privatekey_path: '{{ kafka_ssl_ca_directory }}/ca-key'
    privatekey_passphrase: '{{ ca_password }}'
    csr_path: '{{ kafka_ssl_ca_directory }}/ca-csr'
    selfsigned_not_after: '{{ cert_validity }}'
    provider: selfsigned
    owner: kafka
    group: kafka
    mode: '0640'
    return_content: true
  register: ca_crt
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - ca_cert

# gen ssl keys

- name: generate server key
  community.crypto.openssl_privatekey:
    path: '{{ kafka_ssl_key_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.key'
    owner: kafka
    group: kafka
    mode: '0600'
    return_content: true
  tags:
    - server_cert

- name: generate client key
  community.crypto.openssl_privatekey:
    path: '{{ kafka_ssl_key_directory }}/{{ item }}.key'
    owner: kafka
    group: kafka
    mode: '0600'
  with_flattened:
    - '{{ client_list }}'
    - connect-mirror-maker
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - client_cert

# gen csrs

- name: generate server csr
  community.crypto.openssl_csr:
    path: '{{ kafka_ssl_req_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.csr'
    privatekey_path: '{{ kafka_ssl_key_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.key'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ hostname_map[inventory_hostname].instance.hostname }}'
    use_common_name_for_san: false
    subject_alt_name: '{{ ((["DNS:"] | product(hostname_map[inventory_hostname].instance.aliases)) + ["IP:" + hostname_map[inventory_hostname].instance.ip_pub1]) | map("join") }}'
    owner: kafka
    group: kafka
  tags:
    - server_cert

- name: generate client csr
  community.crypto.openssl_csr:
    path: '{{ kafka_ssl_req_directory }}/{{ item }}.csr'
    privatekey_path: '{{ kafka_ssl_key_directory }}/{{ item }}.key'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ item }}'
    use_common_name_for_san: false
    owner: kafka
    group: kafka
  with_flattened:
    - '{{ client_list }}'
    - connect-mirror-maker
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - client_cert

# sign cert with ca and get client cert

- name: generate server cert signed with ca cert
  community.crypto.x509_certificate:
    path: '{{ kafka_ssl_cert_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.crt'
    privatekey_path: '{{ kafka_ssl_key_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.key'
    csr_path: '{{ kafka_ssl_req_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.csr'
    ownca_content: '{{ ca_crt.certificate }}'
    ownca_privatekey_content: '{{ ca_key.privatekey }}'
    ownca_privatekey_passphrase: '{{ ca_password }}'
    ownca_not_after: '{{ cert_validity }}'
    provider: ownca
    owner: kafka
    group: kafka
    mode: '0640'
    return_content: true
  register: server_certs
  tags:
    - server_cert

- name: generate client cert signed with ca cert
  community.crypto.x509_certificate:
    path: '{{ kafka_ssl_cert_directory }}/{{ item }}.crt'
    privatekey_path: '{{ kafka_ssl_key_directory }}/{{ item }}.key'
    csr_path: '{{ kafka_ssl_req_directory }}/{{ item }}.csr'
    ownca_path: '{{ kafka_ssl_ca_directory }}/ca-crt'
    ownca_privatekey_path: '{{ kafka_ssl_ca_directory }}/ca-key'
    ownca_privatekey_passphrase: '{{ ca_password }}'
    ownca_not_after: '{{ cert_validity }}'
    provider: ownca
    owner: kafka
    group: kafka
    mode: '0640'
    return_content: true
  with_flattened:
    - '{{ client_list }}'
    - connect-mirror-maker
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - client_cert

# generate pkcs12 file from cert keypair

- name: create server pcks12 file from
  community.crypto.openssl_pkcs12:
    path: '{{ kafka_ssl_keystore_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.keystore.jks'
    friendly_name: '{{ hostname_map[inventory_hostname].instance.hostname }}'
    privatekey_path: '{{ kafka_ssl_key_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.key'
    certificate_path: '{{ kafka_ssl_cert_directory }}/{{ hostname_map[inventory_hostname].instance.hostname }}.crt'
    passphrase: '{{ keystore_password }}'
    action: export
    state: present
    owner: kafka
    group: kafka
  tags:
    - server_cert

- name: create client pcks12 file from
  community.crypto.openssl_pkcs12:
    path: '{{ kafka_ssl_keystore_directory }}/{{ item }}.keystore.jks'
    friendly_name: '{{ item }}'
    privatekey_path: '{{ kafka_ssl_key_directory }}/{{ item }}.key'
    certificate_path: '{{ kafka_ssl_cert_directory }}/{{ item }}.crt'
    passphrase: '{{ keystore_password }}'
    action: export
    state: present
    owner: kafka
    group: kafka
  with_flattened:
    - '{{ client_list }}'
    - connect-mirror-maker
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - client_cert

# create truststore (keytool) with client/server certs to single truststore (server.truststore.jks)

# establish chain of trust
- name: add ca to truststore
  community.general.java_cert:
    cert_path: '{{ kafka_ssl_ca_directory }}/ca-crt'
    keystore_path: '{{ kafka_ssl_truststore_directory }}/server.truststore.jks'
    keystore_pass: '{{ truststore_password }}'
    keystore_create: true
    state: present
    cert_alias: '{{ ca_common_name }}'
    trust_cacert: true
    owner: kafka
    group: kafka
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - ca_cert

- name: add server certs to truststore
  community.general.java_cert:
    cert_content: '{{ server_certs.certificate }}'
    keystore_path: '{{ kafka_ssl_truststore_directory }}/server.truststore.jks'
    keystore_pass: '{{ truststore_password }}'
    keystore_create: true
    state: present
    cert_alias: '{{ hostname_map[inventory_hostname].instance.hostname }}'
    owner: kafka
    group: kafka
  tags:
    - server_cert

- name: add client certs to truststore
  community.general.java_cert:
    cert_path: '{{ kafka_ssl_cert_directory }}/{{ item }}.crt'
    keystore_path: '{{ kafka_ssl_truststore_directory }}/server.truststore.jks'
    keystore_pass: '{{ truststore_password }}'
    state: present
    cert_alias: '{{ item }}'
    owner: kafka
    group: kafka
  with_flattened:
    - '{{ client_list }}'
    - connect-mirror-maker
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  tags:
    - client_cert

- name: getting truststore and keystore for propagation
  fetch:
    src: '{{ item }}'
    dest: 'scripts/{{ item | basename }}'
    flat: yes
  run_once: true
  delegate_to: "{{ groups['kafka'][0] }}"
  loop:
    - '{{ kafka_ssl_truststore_directory }}/server.truststore.jks'
    - '{{ kafka_ssl_keystore_directory }}/connect-mirror-maker.keystore.jks'

- name: propagate truststore and keystore to cluster
  copy:
    src: 'scripts/{{ item | basename }}'
    dest: '{{ item }}'
    owner: kafka
    group: kafka
  when: inventory_hostname != groups['kafka'][0]
  loop:
    - '{{ kafka_ssl_truststore_directory }}/server.truststore.jks'
    - '{{ kafka_ssl_keystore_directory }}/connect-mirror-maker.keystore.jks'

- name: removing truststore and keystore from ansible controller
  file:
    path: 'scripts/{{ item }}'
    state: absent
  run_once: true
  delegate_to: localhost
  loop:
    - 'server.truststore.jks'
    - 'connect-mirror-maker.keystore.jks'
